"""Canonical, backend-neutral alpha-discovery lifecycle."""

from .artifacts import (
    DiscoveryArtifactError,
    DiscoveryArtifactManifest,
    DiscoveryArtifactWriter,
    build_discovery_report,
    build_discovery_summary,
)
from .contracts import (
    CandidateRanking,
    DiscoverySpecification,
    DiscoveryTrial,
    EligibilityPolicy,
    EligibilityRule,
    MetricPreference,
    MinimumDataRequirements,
    ParameterNeighborhoodStability,
    RankingEntry,
    RuleOperator,
    SelectionMetricBasis,
    SelectionPolicy,
    TrialEvaluation,
    TrialProposal,
    TrialStatus,
)
from .search_space import ParameterKind, ParameterSpec, SearchSpace
from .service import (
    DiscoveryRecordStore,
    DiscoveryRunResult,
    DiscoverySearchExecutor,
    GridCandidateGenerator,
    TrialEvaluator,
    analyze_parameter_neighborhood,
    rank_trials,
    run_discovery,
    select_trials,
    validate_framework_components,
)
from .validation import CanonicalValidationRequest, prepare_canonical_validation

__all__ = [
    "CandidateRanking",
    "CanonicalValidationRequest",
    "DiscoveryArtifactError",
    "DiscoveryArtifactManifest",
    "DiscoveryArtifactWriter",
    "DiscoveryRecordStore",
    "DiscoveryRunResult",
    "DiscoverySearchExecutor",
    "DiscoverySpecification",
    "DiscoveryTrial",
    "EligibilityPolicy",
    "EligibilityRule",
    "GridCandidateGenerator",
    "MetricPreference",
    "MinimumDataRequirements",
    "ParameterKind",
    "ParameterNeighborhoodStability",
    "ParameterSpec",
    "RankingEntry",
    "RuleOperator",
    "SearchSpace",
    "SelectionMetricBasis",
    "SelectionPolicy",
    "TrialEvaluation",
    "TrialEvaluator",
    "TrialProposal",
    "TrialStatus",
    "analyze_parameter_neighborhood",
    "build_discovery_report",
    "build_discovery_summary",
    "prepare_canonical_validation",
    "rank_trials",
    "run_discovery",
    "select_trials",
    "validate_framework_components",
]
