"""Library-agnostic research contracts for Architecture V2.

The package defines the boundary between exploratory research backends and the
framework-owned canonical validation pipeline.  It deliberately contains no
backend implementation and imports no optional trading library.
"""

from .candidate import CandidateStatus, ResearchCandidate
from .backends import ResearchBackend
from .contracts import (
    EVIDENCE_ROLE_BY_STAGE,
    EvidenceReference,
    EvidenceStage,
    ResearchContractError,
    ResearchRequest,
    ResearchResult,
)
from .decisions import DecisionKind, PromotionDecision
from .dataset import (
    ASSET_ID_COLUMN,
    TIMESTAMP_COLUMN,
    PanelResearchDataset,
    PredictionEligibilitySpec,
    PredictionIneligibilityReason,
    ResearchDatasetError,
    ResearchDatasetValidationReport,
    ResearchSegment,
    ResearchSegmentPurpose,
    SegmentBoundary,
    compute_research_dataset_fingerprint,
    validate_research_dataset,
)
from .discovery import (
    CandidateRanking,
    CanonicalValidationRequest,
    DiscoveryArtifactError,
    DiscoveryArtifactWriter,
    DiscoveryRunResult,
    DiscoverySpecification,
    DiscoveryTrial,
    EligibilityPolicy,
    EligibilityRule,
    GridCandidateGenerator,
    MetricPreference,
    MinimumDataRequirements,
    ParameterKind,
    ParameterNeighborhoodStability,
    ParameterSpec,
    RuleOperator,
    SearchSpace,
    SelectionMetricBasis,
    SelectionPolicy,
    TrialEvaluation,
    TrialProposal,
    TrialStatus,
    analyze_parameter_neighborhood,
    prepare_canonical_validation,
    rank_trials,
    run_discovery,
    select_trials,
)
from .evidence import (
    CanonicalValidationRecord,
    CheckStatus,
    EvidenceRecord,
    require_usable_final_holdout,
)
from .hypothesis import ResearchHypothesis
from .lifecycle import (
    apply_promotion_decision,
    candidate_lifecycle_schema,
    require_transition_allowed,
    transition_candidate,
)
from .multi_asset import (
    CrossSectionalDiagnosticPolicy,
    CrossSectionalMetricStatus,
    MultiAssetInputError,
    MultiAssetParameterMapping,
    MultiAssetPredictionRecord,
    MultiAssetPreprocessingPolicy,
    MultiAssetResearchError,
    MultiAssetResearchMode,
    MultiAssetResourceLimitError,
    MultiAssetResourcePolicy,
    MultiAssetSearchExecutor,
    compute_cross_sectional_diagnostics,
)
from .robustness import MinimumEvidencePolicy, RobustnessCheck, RobustnessRecord
from .run import (
    ResearchRun,
    ResearchRunStatus,
    SearchMetadata,
    SelectionDirection,
)
from .selection import SelectionRecord, candidate_from_research_result
from .serialization import deterministic_json_dumps, deterministic_json_loads
from .trend_quality import (
    TrendQualityResearchError,
    TrendQualityScorePolicy,
    build_multi_horizon_trend_quality_score,
    evaluate_multi_horizon_trend_quality_score,
)

__all__ = [
    "ASSET_ID_COLUMN",
    "CandidateStatus",
    "CandidateRanking",
    "CanonicalValidationRequest",
    "CanonicalValidationRecord",
    "CheckStatus",
    "CrossSectionalDiagnosticPolicy",
    "CrossSectionalMetricStatus",
    "DecisionKind",
    "DiscoveryArtifactError",
    "DiscoveryArtifactWriter",
    "DiscoveryRunResult",
    "DiscoverySpecification",
    "DiscoveryTrial",
    "EVIDENCE_ROLE_BY_STAGE",
    "EvidenceReference",
    "EvidenceStage",
    "EvidenceRecord",
    "EligibilityPolicy",
    "EligibilityRule",
    "GridCandidateGenerator",
    "MetricPreference",
    "MinimumEvidencePolicy",
    "MinimumDataRequirements",
    "MultiAssetInputError",
    "MultiAssetParameterMapping",
    "MultiAssetPredictionRecord",
    "MultiAssetPreprocessingPolicy",
    "MultiAssetResearchError",
    "MultiAssetResearchMode",
    "MultiAssetResourceLimitError",
    "MultiAssetResourcePolicy",
    "MultiAssetSearchExecutor",
    "ParameterKind",
    "ParameterNeighborhoodStability",
    "ParameterSpec",
    "PromotionDecision",
    "PanelResearchDataset",
    "PredictionEligibilitySpec",
    "PredictionIneligibilityReason",
    "ResearchBackend",
    "ResearchCandidate",
    "ResearchContractError",
    "ResearchDatasetError",
    "ResearchDatasetValidationReport",
    "ResearchHypothesis",
    "ResearchRequest",
    "ResearchResult",
    "ResearchRun",
    "ResearchRunStatus",
    "ResearchSegment",
    "ResearchSegmentPurpose",
    "RobustnessCheck",
    "RobustnessRecord",
    "RuleOperator",
    "SearchSpace",
    "SearchMetadata",
    "SelectionDirection",
    "SelectionMetricBasis",
    "SelectionPolicy",
    "SelectionRecord",
    "SegmentBoundary",
    "TIMESTAMP_COLUMN",
    "TrendQualityResearchError",
    "TrendQualityScorePolicy",
    "TrialEvaluation",
    "TrialProposal",
    "TrialStatus",
    "analyze_parameter_neighborhood",
    "apply_promotion_decision",
    "candidate_from_research_result",
    "candidate_lifecycle_schema",
    "compute_research_dataset_fingerprint",
    "compute_cross_sectional_diagnostics",
    "deterministic_json_dumps",
    "deterministic_json_loads",
    "build_multi_horizon_trend_quality_score",
    "evaluate_multi_horizon_trend_quality_score",
    "prepare_canonical_validation",
    "rank_trials",
    "require_transition_allowed",
    "require_usable_final_holdout",
    "run_discovery",
    "select_trials",
    "transition_candidate",
    "validate_research_dataset",
]
